opam-version: "2.0"

synopsis:
  "OCamlEditor is a GTK+ source code editor and build tool for OCaml"
description:
  """It provides many features to facilitate editing code, accessing API reference
directly from the editor and compiling projects."""

authors: ["OCamlEditor developers"]
maintainer: ["OCamlEditor developers"]

license: "LGPL-3.0-only"
homepage: "https://github.com/ocamleditor/ocamleditor"
bug-reports: "https://github.com/ocamleditor/ocamleditor/issues"
dev-repo: "git+https://github.com/ocamleditor/ocamleditor.git"

build: [["ocaml" "build.ml" "ocamleditor"]]
install: [["ocaml" "tools/install.ml" "-prefix" prefix]]

depends: [
  "ocaml" {>= "5.4.0" & <= "5.5.0"}
  "odoc-parser"
  "ocamlfind" 
  "lablgtk3" 
  "ocp-indent" 
  "ocp-index" 
  "xml-light" {>= "2.5"}
  "yojson" 
  "atdgen" 
  "ocamldiff" {>= "1.2"}
  "merlin" 
  "inotify"
  "ocurl"
  "ppx_deriving"
]

