name: Build and Install

on:
  push:
    branches: [ "develop" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure OCaml and Opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.5.0

      - name: Build only
        run: |
          sudo apt-get update -qq
          opam install . --deps-only
          opam exec -- ocaml build.ml ocamleditor 
        

